### ISSUE TITLE
obabel missing libraries

### ISSUE THREAD

**Issue by jw-feng** [chemalot/chemalot#1]
I am running centos 7 and the obabel binary from chemalot did not run due to missing libraries.  Should we ask users to install their own obabel instead of including a binary in the package?

**Comment by bgobbi** [comment]
I would agree.

**Comment by greatlse** [comment]
no OEChem Java library available, any other alternative tools?

**Comment by bgobbi** [comment]
There is no out of the box alternative to OEChem at the moment. The RDKit package provides much of the functionality that the OEChem library provides but the API is different. We have thought about building a set of interfaces that encapsulate the functionality and allow for flexibility in the underlying chemical library but at this point we do not have any immediate intention to implement anything like that.
