### ISSUE TITLE
add SMARTS filters for substructure alerts

### ISSUE THREAD

**Issue by klexa** [chemalot/chemalot#11]
JW & I compiled and pressure-tested a list of SMARTS filters for flagging compounds as a showstopper, red flag, caution, or okay. These filters are meant to be used with sdfStructureTagger.csh

Here's the .sma file in question (with .txt appended since GitHub won't take .sma). This could go in a smarts/ folder.
[OE_RLewis.sma.txt](https://github.com/chemalot/chemalot/files/3499347/OE_RLewis.sma.txt)

**Comment by bgobbi** [comment]
I added this to the config/smarts folder.

Sorry it took me so long to do this!
