### ISSUE TITLE
BUILD FAILED. Outdated class in OpenEye new version?

### ISSUE THREAD

**Issue by giaguaro** [chemalot/chemalot#12]
Hi,

I was wondering if there is a way to circumvent this error message? 

    [javac] /home/hmslati/chemalot/chemalot/build.xml:53: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 112 source files to /home/hmslati/chemalot/chemalot/classes
    [javac] /home/hmslati/chemalot/chemalot/src/com/genentech/chemistry/openEye/apps/SDFMDLSSSMatcher.java:153: error: cannot find symbol
    [javac]    {  oechem.OEUseJavaHeap(false);
    [javac]             ^
    [javac]   symbol:   method OEUseJavaHeap(boolean)
    [javac]   location: class oechem

I was thinking the only way to resolve this is by finding the 2014 version of OpenEye.

Could you please help me with this issue?
Thank you.

**Comment by bgobbi** [comment]
You can simply remove that line. We are still using the 2018 version of the toolkit.

**Comment by giaguaro** [comment]
Thank you! That's what i did. It was resolved! I also did get OE version 2014.
