### ISSUE TITLE
noTautomerize option in sdfNormalizer

### ISSUE THREAD

**Issue by jw-feng** [chemalot/chemalot#2]
Hi Alberto,

I want to use sdfNormalizer but I don't have a Quacpac license.   I can disable tautomer calculation by commenting out the following in Struchk.xml
   <tautomerize id='tautomerize' >
      <example>Cc1[nH]nc(CC)c1</example>
      <description>Generate canonical tautomer using quacpac.</description>
   </tautomerize>

I started implementing a noTautomerize option for sdfNormalizer.java but I thought I check with you before going too far.  I know this is critical code for GNE registration and didn't want to make too many changes.  What do you think is the best way to give user the option to no tautomerize?   I could use another tautomerization tool to generate a canonical tautomer and then call sdfNormalizer.csh to perform the rest of normalization. 

Thanks,

JW

**Comment by bgobbi** [comment]
I added the -f option to the sdfNormalizer.  You can now use a modified version of struchk.xml with the tautomerization task commented out.
Please note that you will still have to use the CTI and CTSMILES as those are the last smiles produced in the process.
