### ISSUE TITLE
R model building tools require quacpac

### ISSUE THREAD

**Issue by jw-feng** [chemalot/chemalot#5]
sdfRRandomForestCreator.pl, sdfRSVMCreator.pl, sdfRModelPredictor.pl all require a quacpac license.  Is quacpac really necessary?

**Comment by bgobbi** [comment]
The only place the whole chemalot package uses quacpac is in sdfNormalizer. I thought you had implemented a version that does not use it. You will be missing the tautomer detection but if that is not important to you everything else will be fine.
In fact I think the use of sdfNormalizer inside the model creators is not really required. It is there to keep a file with the TISMILES of the training set in case you want a quick way to lookup if a compound was in the training set. As far as I could see in a quick glance it is never used at this point.
