### ISSUE TITLE
Counter start position

### ISSUE THREAD

**Issue by klexa** [chemalot/chemalot#6]
Rather than the current hard-coded value of zero, would it be possible to add another variable to the sdfTagTool code to specify the starting number from which to begin iterating over?

For instance:
sdfTagTool.csh -in .sdf -counterTag counter -addCounter **_-start 50_** -out .sdf

@jw-feng

**Comment by bgobbi** [comment]
If we which to do so I would suggest that we call it something like -counterStart to make it more clear what this is referring to. An alternative would be to use a sdfGroovy to increment the counter by eg. 50.
Would that work for you? I would hesitate to make the options in the tag tool more complicated unless you feel this is a frequent use case.
Alberto

**Comment by jw-feng** [comment]
@bgobbi 
I just implemented -counterStart in SdfTagTool.java in the autocorrelator package.   I also added a markAsRepeatTag option to mark repeated records by tag.  I created a branch named sdfTagTool, committed my changes, and created a pull request.  Can you review and approve the pull request?
